language: node_js
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'create database riders_ah_db;' -U postgres

script:
  - npm run test
  
after_success:
  - npm run coverage
